### ISSUE TITLE
example (m/? (m/sleep 1000 42)) does not work in clojurescript

### ISSUE THREAD

**Issue by FongHou** [leonoel/missionary#2]
An exception is thrown from [here](https://github.com/leonoel/missionary/blob/1c7b771ef9cc250804a40b6c6145818822e019b7/src/missionary/impl.cljs#L214)

Tried to set a breakpoint on this [line](https://github.com/leonoel/missionary/blob/1c7b771ef9cc250804a40b6c6145818822e019b7/src/missionary/impl.cljs#L195) in chrome debugger, but the breakpoint was never hit. It seems closed over fiber variable never gets a not nil value.

**Comment by leonoel** [comment]
This is intended. `?` is parking when used inside a `sp` block and blocking elsewhere. In clojurescript, blocking is not supported so you can't use `?` outside of a `sp` block.
I'm currently working on a documentation rewrite, I'll make sure this point is made more explicit.

**Comment by leonoel** [comment]
Tutorial Hello task hopefully makes this point more explicit.
