### ISSUE TITLE
amb operators, sequential and parallel

### ISSUE THREAD

**Issue by leonoel** [leonoel/missionary#27]
Just syntactic sugar. Inside an `ap` block, `amb?` and `amb=` evaluate an arbitrary number of branches ambiguously, respectively sequentially or in parallel.

```clojure
(defmacro amb? [& forms]
  `(case (m/?? (m/enumerate (range ~(count forms))))
     ~@(interleave (range) forms)))
```

```clojure
(defmacro amb= [& forms]
  `(case (m/?= (m/enumerate (range ~(count forms))))
     ~@(interleave (range) forms)))
```

**Comment by xificurC** [comment]
`amb?` looks like a predicate, which confuses my brain. How about one of

- `?amb?` and `?amb=`. It keeps your current symbolic style but injects the word "amb"
- `?amb` and `=amb`. It keeps the symbolic meaning of `?` for sequential and `=` for concurrent forking but puts it at the beginning of the symbol.
- a completely new symbol to mean amb, e.g. `+` that looks like the midpoint is splitting into multiple directions, turning into `+?` and `+=`.

**Comment by leonoel** [comment]
I would discard the third option because `amb` is an old and known idea, so hiding it behind a symbol is likely to add confusion for nothing. Please share your thoughts about naming in general in #29

**Comment by leonoel** [comment]
released `b.19`
