### ISSUE TITLE
ditch gather

### ISSUE THREAD

**Issue by leonoel** [leonoel/missionary#28]
`gather` was useful before `ap`/`?=` was a thing, much less now, especially considering `amb=`.

**Comment by xificurC** [comment]
Can you elaborate what pattern would substitute `gather`'s usage? I'm working on the RxJava comparison tutorial and the next example merges two `Observable`s, which seems what `gather` does. After thinking for 10 minutes and sifting through the API I haven't found another way to merge 2 flows.

**Comment by xificurC** [comment]
Nevermind, I see gather is implemented as

```clojure
([f & fs] (ap (?? (?= (enumerate (cons f fs))))))
```

Now just to understand that :)

**Comment by xificurC** [comment]
`enumerate` turns a list of flows into a flow of flows. `?=` forks the flow of flows into flows running concurrently. `??` picks the next value in each forked process. Not bad.

With `amb=` this would be `(ap (?? (amb= f1 f2 f3 ...)))`, right?

**Comment by leonoel** [comment]
deprecated `b.19`

**Comment by dustingetz** [comment]
`(defn mix [& flows] (m/ap (m/?> (m/?> (count flows) (m/seed flows)))))`

**Comment by dustingetz** [comment]
Leo says: "I want to minimize the surface API and encourage usage of primitive operators instead. If this operator exists then a dozen of other combinations deserve to exist too"
