### ISSUE TITLE
destructuring in let bindings breaks `sp`

### ISSUE THREAD

**Issue by noonian** [leonoel/missionary#59]
```
(m/sp (let [{:keys [x]} {}]))
```

throws  

```
Syntax error macroexpanding cloroutine.core/cr at (REPL:1:1).
No matching clause: :static-field
```
If this is not supported then maybe it just needs to be documented.

**Comment by leonoel** [comment]
Thanks. It's a bug in cloroutine, the implementation for static field access is missing.

**Comment by leonoel** [comment]
Fixed in `b.27`
