### ISSUE TITLE
zip doesn't terminate properly

### ISSUE THREAD

**Issue by leonoel** [leonoel/missionary#74]
`(m/zip vector (m/seed [1 2 3]) (m/seed (repeat nil)))` goes into an infinite loop when 3 gets consumed.

**Comment by xificurC** [comment]
`(m/? (m/reduce conj (interleave (m/seed [0 0 0]) (m/seed (range 99999999)))))` takes 3 seconds to finish, suggesting `m/zip` eagerly consumes its upstream flows, but producing the correct answer.

**Comment by xificurC** [comment]
I believe I captured the essence here

https://github.com/leonoel/missionary/commit/595ca7b412ccff1f09b539a356f9e23ef730bc6d

**Comment by leonoel** [comment]
Fixed in `b.39`
