### ISSUE TITLE
Hello task example prints only Hello with Clojure repl 

### ISSUE THREAD

**Issue by PEZ** [leonoel/missionary#91]
When I try this:

```clojure
  (def slowmo-hello-world
    (m/sp (println "Hello")
          (m/? nap)
          (println "World")
          (m/? nap)
          (println "!")))

  (let [begin (System/currentTimeMillis)]
    (m/? slowmo-hello-world)
    (println "Took: " (- (System/currentTimeMillis) begin) " ms"))
```

I get this:

```
Hello
Took:  2005  ms
=> nil
```

It works as expected in the ClojureScript repl.

**Comment by PEZ** [comment]
Probably goes without saying, but anyway:

```clojure
  (def chatty-hello-world
    (m/join vector slowmo-hello-world slowmo-hello-world))
  
  (m/? chatty-hello-world)
Hello
Hello
=> [nil nil]
```

Again, the naps are taken as I expect.

**Comment by dustingetz** [comment]
The subsequent printlns are logged to the terminal, suggesting the issue is an interaction with how Calva rebinds stdout to redirect it to the REPL buffer
![image](https://github.com/leonoel/missionary/assets/124158/4e478791-4cb1-4b65-8c7f-a1c103fce0c2)

**Comment by dustingetz** [comment]
IIRC, Geoffrey said that cider used to have this issue and fixed it in the last year (?), the toolchain stack is complex and we are not experts in this so it's hard for me to say exactly which layer is the root cause

**Comment by PEZ** [comment]
Thanks, @dustingetz . If CIDER can do the right thing, so can Calva. 

Sorry for the noise, @leonoel !
